# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyspeed < Formula
  desc "Terminal-based internet speed test"
  homepage "https://github.com/jkleinne/lazyspeed"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v0.4.1/lazyspeed_0.4.1_darwin_amd64.tar.gz"
      sha256 "a657778aab8a37bedc02509b1972bfca122c0a8a2f0d6c2e139d2611ebddd424"

      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v0.4.1/lazyspeed_0.4.1_darwin_arm64.tar.gz"
      sha256 "787835e21f0757ee291b9eb0bbfc7a90aa9342c54f9a351aa826f426a1ee8c6f"

      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v0.4.1/lazyspeed_0.4.1_linux_amd64.tar.gz"
      sha256 "0c85a01cf9f96dec15dc8eb4cab0f37440548676ae7268c61b8d82fb2408ba6d"
      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v0.4.1/lazyspeed_0.4.1_linux_arm64.tar.gz"
      sha256 "879ad824654519797819e4469bf9f810249fa3e7a27b43772b8ea2e7e76fdc8e"
      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
  end

  test do
    assert_match "lazyspeed version", shell_output("#{bin}/lazyspeed version")
  end
end
