# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyspeed < Formula
  desc "Terminal-based internet speed test"
  homepage "https://github.com/jkleinne/lazyspeed"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v1.3.1/lazyspeed_1.3.1_darwin_amd64.tar.gz"
      sha256 "1a76f0f70580e0b640870733b490dd25874db2c6c38316801b7ea3143fa3cf33"

      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v1.3.1/lazyspeed_1.3.1_darwin_arm64.tar.gz"
      sha256 "efd32b4a2f4f23127300288497b3ab93edd6c6c6262d51b25478fb659082c7d5"

      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v1.3.1/lazyspeed_1.3.1_linux_amd64.tar.gz"
      sha256 "db204547dba64c7a12ec50c4b42724d3b061d816646b452ce784343c25cf54b4"
      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/lazyspeed/releases/download/v1.3.1/lazyspeed_1.3.1_linux_arm64.tar.gz"
      sha256 "935f16c7f8afccc825f032cfc9197ee7cf8fdc6cb2c76bf514f4b81e5f3cac28"
      define_method(:install) do
        bin.install "lazyspeed"
      end
    end
  end

  test do
    assert_match "lazyspeed version", shell_output("#{bin}/lazyspeed version")
  end
end
