# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shuttle < Formula
  desc "Personal backup and sync CLI for rsync and rclone via TOML config"
  homepage "https://github.com/jkleinne/shuttle"
  version "0.2.4"
  license "MIT"

  depends_on "rclone"
  depends_on "rsync"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.4/shuttle_0.2.4_darwin_x86_64.tar.gz"
      sha256 "b72221907cd459a7e5e41b4e2e33ef041b6dd19164dfbf3ada09a3a4673df3da"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.4/shuttle_0.2.4_darwin_arm64.tar.gz"
      sha256 "5d347714f68deee135569e84dbfe77e3266035bb866c9cacdbfbad12f60bf54a"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.4/shuttle_0.2.4_linux_x86_64.tar.gz"
      sha256 "ab96226845fa1a2452cc5b38d2209fa49c0f7467fbd3d30632485e7fe736c81d"
      define_method(:install) do
        bin.install "shuttle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.4/shuttle_0.2.4_linux_arm64.tar.gz"
      sha256 "8d39c86593c2f78dba1f58b94999963f39c808558192e7170e9c422885615665"
      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  test do
    system "#{bin}/shuttle", "version"
  end
end
