# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shuttle < Formula
  desc "Personal backup and sync CLI for rsync and rclone via TOML config"
  homepage "https://github.com/jkleinne/shuttle"
  version "0.2.1"
  license "MIT"

  depends_on "rclone"
  depends_on "rsync"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.1/shuttle_0.2.1_darwin_x86_64.tar.gz"
      sha256 "cbbdd5df80514cd2fd5959f7ee951f7cf341ef728624bfcf6683dda39adcfc63"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.1/shuttle_0.2.1_darwin_arm64.tar.gz"
      sha256 "8cc84cdd4f8cefcc2ae49f323fbc49e0430c830a188dc517aab339dbd23a9c03"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.2.1/shuttle_0.2.1_linux_x86_64.tar.gz"
      sha256 "74edc35e8f2bf24cf12fca325027d8b6d73205211dfd4ca17608e7fec231fda2"
      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  test do
    system "#{bin}/shuttle", "version"
  end
end
