# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shuttle < Formula
  desc "Personal backup and synchronization CLI orchestrating rsync and rclone via a single TOML config"
  homepage "https://github.com/jkleinne/shuttle"
  version "0.1.0"
  license "MIT"

  depends_on "rclone"
  depends_on "rsync"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.1.0/shuttle_0.1.0_darwin_x86_64.tar.gz"
      sha256 "ab84bc8a984adb3091f699a2a1225a841506d63c4317e7e56a0b6eacd107400c"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.1.0/shuttle_0.1.0_darwin_arm64.tar.gz"
      sha256 "0e10e71b5bce3cc7928db778a874ecf80473a38a73b184fe8db30815e92eb4c1"

      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jkleinne/shuttle/releases/download/v0.1.0/shuttle_0.1.0_linux_x86_64.tar.gz"
      sha256 "9c66e38f5da9bb55772b3c53526a6400e5b731b05d9d4358a3340c98a143e71e"
      define_method(:install) do
        bin.install "shuttle"
      end
    end
  end

  test do
    system "#{bin}/shuttle", "version"
  end
end
